import { getPages } from "@/sanity/sanity-utils";
import Link from "next/link";
import '../globals.css';

export const metadata = {
  title: 'Recep Yolcu Projects',
  description: 'Generated by next + sanity',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const pages = await getPages();

    return (
        <html lang="en">
            <body className='bg-neutral-900 text-white'>
                <header className="w-10/12 mx-auto py-4 px-1 flex justify-between items-center border-b-[3px] border-neutral-800 shadow-xl">
                    <div>
                        <h1 className="text-xl font-semibold">Ryo</h1>
                    </div>
                    <nav>
                        <ul className="flex gap-6 items-center">
                            <li><Link href={"/"}>Home</Link></li>
                            {pages.map((page) => (
                                <Link key={page._id} href={`/${page.slug}`}>
                                    {page.title}
                                </Link>
                            ))}
                        </ul>
                    </nav>
                </header>
                <main className='w-10/12 mx-auto py-20'>
                    {children}
                </main>
            </body>
        </html>
    )
}
